//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.InvoiceItems = new HashSet<InvoiceItem>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int JewelTypeId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string CaratWeight { get; set; }
        public string GoldWeight { get; set; }
        public string GoldContent { get; set; }
        public string Pieces { get; set; }
        public string DiamondPieces { get; set; }
        public string DateReceived { get; set; }
        public string Price { get; set; }
        public int InventoryStatusId { get; set; }
        public byte[] Image { get; set; }
        public string Description { get; set; }
        public string CategoryNumber { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> MISC1 { get; set; }
        public string MISC2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }
    }
}
