//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePayment
    {
        public int Id { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string Cash { get; set; }
        public string CreditCard { get; set; }
        public string Cheque { get; set; }
        public string PaymentAmount { get; set; }
        public string NewInvoiceId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> MISC1 { get; set; }
        public string MISC2 { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
