//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceItems = new HashSet<InvoiceItem>();
            this.InvoicePayments = new HashSet<InvoicePayment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string SubTotal { get; set; }
        public string Cheque { get; set; }
        public string CreditCard { get; set; }
        public string Cash { get; set; }
        public string TotalAmount { get; set; }
        public string Balance { get; set; }
        public int UserId { get; set; }
        public int InventoryStatusId { get; set; }
        public string TaxType { get; set; }
        public string LayAwayInvoiceId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> MISC1 { get; set; }
        public string MISC2 { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual InventoryStatu InventoryStatu { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePayment> InvoicePayments { get; set; }
    }
}
